# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:

  proto_mapper_generator:
    import: "package:proto_generator/proto_generator.dart"
    builder_factories: ["protoMapperBuilder"]
    build_extensions: {".dart": ["proto_map.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  proto_generator:
    import: "package:proto_generator/proto_generator.dart"
    builder_factories: ["protoBuilder"]
    build_extensions: {".dart": [".proto"]}
    auto_apply: dependents
    build_to: source

  proto_services_generator:
    import: "package:proto_generator/proto_generator.dart"
    builder_factories: ["protoServicesBuilder"]
    build_extensions: {".dart": ["proto_services.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
