builders:

  entity_adapter_generator:
    import: "package:squarealfa_entity_adapter_generator/squarealfa_entity_adapter_generator.dart"
    builder_factories: ["entityAdapterBuilder"]
    build_extensions: {".dart": ["entity_adapter.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  map_map_generator:
    import: "package:map_mapper_generator/map_mapper_generator.dart"
    builder_factories: ["mapMapBuilder"]
    build_extensions: {".dart": ["entity_map.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  proto_mapper_generator:
    import: "package:proto_generator/proto_generator.dart"
    builder_factories: ["protoMapperBuilder"]
    build_extensions: {".dart": ["entity_proto_map.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  proto_generator:
    import: "package:proto_generator/proto_generator.dart"
    builder_factories: ["protoBuilder"]
    build_extensions: {".dart": [".entity.proto"]}
    auto_apply: dependents
    build_to: source

  defaults_provider_generator:
    import: "package:defaults_provider_generator/defaults_provider_generator.dart"
    builder_factories: ["defaultsProviderGeneratorBuilder"]
    build_extensions: {".dart": ["entity_defaults_provider.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  validation_generator:
    import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
    builder_factories: ["validationGeneratorBuilder"]
    build_extensions: {".dart": ["entity_validation.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  builder_generator:
    import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
    builder_factories: ["builderBuilder"]
    build_extensions: {".dart": ["entity_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  copywith_generator:
    import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
    builder_factories: ["copyWithBuilder"]
    build_extensions: {".dart": ["entity_copywith.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

